# ---------- Build Stage ----------
FROM node:20 AS base

WORKDIR /app

COPY ./frontend/package*.json ./

RUN npm ci

COPY ./frontend .

# Build arguments
ARG REACT_APP_KONG_KEY
ARG REACT_APP_KONG_URL

# React environment variables
ENV REACT_APP_KONG_KEY=$REACT_APP_KONG_KEY
ENV REACT_APP_KONG_URL=$REACT_APP_KONG_URL

# Build React app
RUN npm run build

# ---------- Production Stage ----------
FROM nginx:alpine AS prod

# Remove default nginx files
RUN rm -rf /usr/share/nginx/html/*

# Copy React build
COPY --from=base /app/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
 
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
